name: Deploy to Amazon ECS

on:
  push:
    branches: [ "gh-pages" ]

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: eoagritool
  ECS_SERVICE: deploy
  ECS_CLUSTER: deploy
  ECS_TASK_DEFINITION: aws.yml
  CONTAINER_NAME: eoagritool

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Amazon ECS
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Attach Administrator Policy to IAM User
        run: |
          aws iam attach-user-policy --user-name aimty --policy-arn arn:aws:iam::aws:policy/AdministratorAccess

      - name: Run AWS CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: EOAgriTool
          buildspec-override: buildspec.yml
          aws-region: ${{ env.AWS_REGION }}
          compute-type: "BUILD_GENERAL1_SMALL"
          environment-type: "LINUX_CONTAINER"
          image: "aws/codebuild/ami/amazonlinux-x86_64-base:latest"
          service-role: "arn:aws:iam::915704192506:role/service-role/codebuild-EOAgriTool-service-role"
          timeout-in-minutes: 15
          queued-timeout-in-minutes: 480
          logs-config:
            cloudwatch:
              group-name: "/aws/codebuild/EOAgriTool"
              enabled: true
          artifacts:
            type: "S3"
            location: "arn:aws:s3:::elasticbeanstalk-us-west-2-915704192506/400c8f25-11ae-40c6-91f4-b5ff8108d6c8/EOAgriTool"
            encryption-disabled: false

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
